application: mayacs-test
version: briefme-p-3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: static/index.html
  upload: static/index.html
  login: required
- url: /(.*\.(html|js|css|gif))$
  static_files: static/\1
  upload: static/.*\.(html|js|css|gif)$
  login: required
- url: /create-item
  script: briefme.httpserver.application
  login: admin
- url: /.*
  script: briefme.httpserver.application
  login: required

libraries:
- name: webapp2
  version: latest
